version: "3.7"
services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.2-arm64
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - "discovery.type=single-node"
      - "cluster.name=personium-cluster"
      - "network.host=0.0.0.0"
      - "action.auto_create_index=.watches,.triggered_watches,.watcher-history-*"
      - "http.cors.enabled=true"
      - "http.cors.allow-origin=*"
      - "indices.fielddata.cache.size=80%"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "curl --fail localhost:9200/_cat/health?h=status | grep green || exit 1"]
      interval: 30s
      timeout: 30s
      retries: 10

  activemq:
    image: symptoma/activemq:5.16.2-multiarch
    ports:
      - 61616:61616
      - 8161:8161
    networks:
      - mq
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail localhost:8161 || exit 1"]
      interval: 30s
      timeout: 30s
      retries: 10

  personium-core:
    build: ./tomcat-wait-for-elasticsearch
    networks:
      - frontend
      - mq
      - backend
    depends_on:
      - elasticsearch
      - activemq
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail localhost:8080/personium-core || exit 1"]
      interval: 30s
      timeout: 30s
      retries: 10
    environment:
      - JAVA_OPTS=-Dio.personium.configurationFile=/personium/personium-core/conf/personium-unit-config.properties
    volumes:
      - personium_nfs:/personium_nfs
      - type: bind
        source: ../personium-core/target/personium-core.war
        target: /usr/local/tomcat/webapps/personium-core.war
      - type: bind
        source: ./personium-core/personium-unit-config.properties
        target: /personium/personium-core/conf/personium-unit-config.properties
      - type: bind
        source: ./personium-core/x509/unit-self-sign.crt
        target: /opt/x509/unit-self-sign.crt
      - type: bind
        source: ./personium-core/x509/unit.key
        target: /opt/x509/unit.key

  personium-engine:
    build: ./tomcat-wait-for-elasticsearch
    environment:
      - JAVA_OPTS=-Dio.personium.configurationFile=/personium/personium-engine/conf/personium-unit-config.properties
    volumes:
      - personium_nfs:/personium_nfs
      - type: bind
        source: ../personium-engine/target/personium-engine.war
        target: /usr/local/tomcat/webapps/personium-engine.war
    networks:
      - backend

  nginx:
    build: nginx
    ports:
      - 443:443
      - 80:80
    networks:
      - frontend
    depends_on:
      - personium-core
    volumes:
      - type: bind
        source: ./nginx/server.crt
        target: /etc/nginx/server.crt
      - type: bind
        source: ./nginx/server.key
        target: /etc/nginx/server.key

volumes:
  esdata:
    driver: local
  personium_nfs:
    driver: local

networks:
  frontend:
  mq:
  backend: